### ISSUE TITLE
connect node.js server with terminal in lively

### ISSUE THREAD

**Issue by JensLincke** [LivelyKernel/lively4-services#1]
1. open interactive node.js terminal on lively4 website
2. type aync code that runs for a while and press enter 
3. see console.log messages and errors on terminal as the code is executed

**Comment by JensLincke** [comment]
what we talked about ... @philippotto @fniephaus

**Comment by fniephaus** [comment]
We are now using [xterm.js](https://github.com/sourcelair/xterm.js) for this.
